services:

  backend:
    build: ./services/backend
    ports:
      - 5555:5555
    volumes:
      - ./services/backend:/code
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 5555"
    depends_on:
    - db

  frontend:
    build: ./services/frontend
    ports:
      - 8080:8080
    volumes:
      - ./services/frontend:/app
      - /app/node_modules

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo_db
    ports:
      - 5432:5432
    volumes:
      - ./db_dump/init.sql:/docker-entrypoint-initdb.d/init.sql